name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Staging

    steps:
    - name: SSH into EC2 instance and deploy Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Docker
          sudo apt update
          sudo apt install -y docker.io

          # Clone the repository
          git clone https://github.com/irreducible-leaf/mnist-overkill.git
          cd mnist-overkill

          # Build and push Docker image
          sudo docker build -t my-gradio-app .
          
          # Pull and run Docker image
          sudo docker run -d -p 8080:8080 --name my-gradio-app my-gradio-app
